#pragma once
#define DICE_H

#include "stdafx.h"
#include <vector>

/**
* A six-sided die 
*/
class Dice {
private:
	//Total number of 0s rolled by this die
	int zeroCounter;
	//Total number of 1s rolled by this die
	int oneCounter;
	//Total number of 2s rolled by this die
	int twoCounter;
	//Total number of 3s rolled by this die
	int threeCounter;
public:
	/** Default constructor */
	Dice();
	/**
	* Returns a random number generated by a six-sided die
	* @return A random int between 1 and 6
	*/
	int roll();
	/**
	* Prints the rolling rate for each possible outcome
	*/
	void printRollPercentage();
};